apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  destination:
    server: "https://kubernetes.default.svc"
  source:
    path: overlays/k3s
    repoURL: https://github.com/sekthor/cert-manager.git
    targetRevision: HEAD
  project: default
