apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

bases:
  - ../../base/

resources:
  - ingress.yaml
  - applications/dev-minio.yaml

patches:
  #- patches/argocd-cm.yaml
  - patches/argocd-param-cm.yaml